### ISSUE TITLE
Cannot find on npmjs.com

### ISSUE THREAD

**Issue by 0x6b** [lostandfound/textlint-rule-ja-hiragana-keishikimeishi#1]
I cannot install this package by `npm` due to 404 error. Could you have a look into the description below and give me your comment?

* * *

# Steps to reproduce

1. Open terminal
2. Run following command as documented at [README.md](https://github.com/lostandfound/textlint-rule-ja-hiragana-keishikimeishi/blob/master/README.md)

```sh
npm install textlint-rule-ja-hiragana-keishikimeishi
```

# Expected result

Successful installation without error.

# Actual result

```sh
> npm install textlint-rule-ja-hiragana-keishikimeishi
npm ERR! code E404
npm ERR! 404 Not Found: textlint-rule-ja-hiragana-keishikimeishi@latest
```

I cannot find the package on [npmjs.com/search?q=textlint-rule-ja-hiragana-keishikimeishi](https://www.npmjs.com/search?q=textlint-rule-ja-hiragana-keishikimeishi).

# Environments

- npm 5.0.3
- node 8.1.2
- textlint 8.2.1

* * *

I presume I'm doing something wrong. If you need anything else please let me know.

**Comment by lostandfound** [comment]
Hi.

I asked Npmjs support what's wrong with my repositry, because its download counts had kept zero. Npmjs support answered that the downloads counts for a package will remain as 0 for the first 24 hours, then will update.

I'm not satisfied with their answer, because its download counts had been zero for these 7 months. Anyway, my package infromation was updated today and you can find it in <https://www.npmjs.com/search?q=textlint-rule-ja-hiragana-keishikimeishi>. 

Would you please try `npm insall` again?

**Comment by 0x6b** [comment]
Hi @lostandfound,

I successfully can install the package as expected:

```sh
> npm install textlint-rule-ja-hiragana-keishikimeishi
+ textlint-rule-ja-hiragana-keishikimeishi@1.0.2
added 1 package in 3.931s
```

I also can find the package on [npmjs.com/search?q=textlint-rule-ja-hiragana-keishikimeishi](https://www.npmjs.com/search?q=textlint-rule-ja-hiragana-keishikimeishi).

Thank you very much for your prompt help!
